host: "xxxxxxxxxx-ats.iot.eu-west-1.amazonaws.com"
rootCAPath: "~/.secrets/iot/AmazonRootCA1.pem"
certificatePath: "~/.secrets/iot/certificate.pem.crt"
privateKeyPath: "~/.secrets/iot/private.pem.key"
thingName: "v01"
clientId: "v01"
actions:
  - camara:
      type:   "bash"
      on:     "touch /tmp/camara.tmp"
      off:    "rm /tmp/camara.tmp"
  - foco:
      type:   "socket"
      socket: "/tmp/channel0"
      on:     "10;1111"
      off:    "0;0000"
  