host: "xxxxxxxxxx-ats.iot.eu-west-1.amazonaws.com"
rootCAPath: "/etc/mything/AmazonRootCA1.pem"
certificatePath: "/etc/mything/certificate.pem.crt"
privateKeyPath: "/etc/mything/private.pem.key"
thingName: "v01"
clientId: "v01"
actions:
  camara:
    type:      "bash"
    "on":      "touch /tmp/camara.tmp"
    "off":     "rm /tmp/camara.tmp"
    "autoOff": false
  foco:
    type:      "socket"
    socket:    "/tmp/channel0"
    "on":      "D0;10;1111"
    "off":     "D0;0;0000"
    "autoOff": true
  
