broker: "192.168.1.19"
alias: { "D0": "ESP3C71BF4D0BB8", 
         "D1": "ESP001D1"}
defaultCmd: [ "D0;0001;0001" ]
tempFile: "/var/lib/balcon/28039.json"
timetable:
  - temp: 30
    hours:  [14,16,20]
    cmd: [ "D0;0040;0010" ]
  - temp: 35
    hours:  [12,18]
    cmd: [ "D0;0040;0010" ]
